/* -----------------------------------------------------------------------------------------------------------------------------------------
                                                        Template File for SQL
  ---------------------------------------------------------------------------------------------------------------------------------------- */

/* CREATING TABLES */

/* creating product table */
 create table public.products (
  "ProductID" bigint generated by default as identity not null,
  "ProductName" text not null,
  "Category" text not null,
  "Description" text null,
  "TotalInventory" integer not null default 0,
  "CostPrice" double precision not null,
  "RetailPrice" double precision not null,
  "Review" text null,
  "Supplier" bigint null,
  constraint products_pkey primary key ("ProductID"),
  constraint products_ProductID_key unique ("ProductID"),
  constraint products_ProductName_key unique ("ProductName"),
  constraint products_Supplier_fkey foreign KEY ("Supplier") references suppliers (id)
) TABLESPACE pg_default;

/* creating account table */
create table public."Account" (
  "UserId" bigint generated by default as identity not null,
  "UserName" text null,
  "Password" text null,
  "EmailAddress" text null,
  constraint Account_pkey primary key ("UserId")
) TABLESPACE pg_default;

/* creating department table */
create table public."Department" (
  "DepartmentID" bigint generated by default as identity not null,
  "DepartmentName" text null,
  "SupervisorID" bigint null,
  constraint Department_pkey primary key ("DepartmentID"),
  constraint Department_SupervisorID_fkey foreign KEY ("SupervisorID") references "Supervisor" ("SupervisorID")
) TABLESPACE pg_default;

/* creating employee table */
create table public."Employee" (
  "EmployeeID" bigint generated by default as identity not null,
  "Name" text null,
  "SSN" bigint null,
  "PhoneNumber" bigint null,
  "Hours" bigint null,
  "HourlyWage" bigint null,
  "RoutingNumber" bigint null,
  "UserID" bigint null,
  "DepartmentID" bigint null,
  constraint Employee_pkey primary key ("EmployeeID"),
  constraint Employee_UserID_fkey foreign KEY ("UserID") references "Account" ("UserId")
) TABLESPACE pg_default;

/* creating member table */
create table public."Member" (
  "MemberID" bigint generated by default as identity not null,
  "Name" text null,
  "Birthday" date null,
  "PhoneNumber" bigint null,
  "BillingAddress" text null,
  "ShippingAddress" text null,
  "LoyaltyPoints" double precision null,
  "PaymentInfo" double precision null,
  "UserID" bigint null,
  constraint Member_pkey primary key ("MemberID"),
  constraint Member_UserID_fkey foreign KEY ("UserID") references "Account" ("UserId")
) TABLESPACE pg_default;

/* creating order table */
create table public."Order" (
  "OrderID" bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "ShippingAddress" text null,
  "BillingAddress" text null,
  "TotalAmount" double precision null,
  "SalesTax" double precision null,
  "ShippingCost" double precision null,
  "PromoCode" bigint null,
  constraint Order_pkey primary key ("OrderID")
) TABLESPACE pg_default;

/* creating supervisor table */
create table public."Supervisor" (
  "SupervisorID" bigint generated by default as identity not null,
  "DepartmentID" bigint null,
  "UserID" bigint null,
  constraint Supervisor_pkey primary key ("SupervisorID"),
  constraint Supervisor_DepartmentID_fkey foreign KEY ("DepartmentID") references "Department" ("DepartmentID"),
  constraint Supervisor_UserID_fkey foreign KEY ("UserID") references "Account" ("UserId")
) TABLESPACE pg_default;

/* creating suppliers table */
create table public."Suppliers" (
  id bigint generated by default as identity not null,
  name text not null,
  constraint suppliers_pkey primary key (id)
) TABLESPACE pg_default;

/* FILLING TABLES */

/* filling product table */
INSERT INTO "public"."Products" ("ProductID", "ProductName", "Category", "Description", "TotalInventory", "CostPrice", "RetailPrice", "Review", "Supplier")
VALUES
    ('1', 'Root to Tip Hair Growth Serum ', 'Wellness', 'Root to tip hair growth serum for strong, healthy and vibrant hair.', '10', '13.13', '42.99', null, '1'),
    ('2', 'Revitalizing Youth Serum', 'Wellness', 'Revitalizing facial serum to restore the signs of youth. Minimizes fine lines, wrinkles, and dark spots. Evens skin tone and reduces hyperpigmintation.  ', '10', '22.22', '69.99', null, '1'),
    ('3', 'Ultra Repair Night Cream', 'Wellnes', 'Hydrating facial moisturizer. Your nightly rescue for tired and dull skin. Restores natural skin barrier. Use nightly on cleansed dry skin. ', '10', '19.19', '54.99', null, '1'),
    ('4', 'Hydrating Lip Balm', 'Wellness', 'Healing lip balm to protect and sooth dry lips.', '10', '4.04', '9.99', null, '1'),
    ('5', 'Soothing Cough Syrup', 'Wellness', 'Healing cough syrup to ease sore throat and suppress cough for a restfulness night sleep. Made with real daisy extract.', '10', '5.05', '27.99', null, '2'),
    ('6', 'Eidos by Zen Daisy', 'Wellness', 'Perfume', '10', '27.27', '89.99', null, '1'),
    ('7', 'Organic Loose Lea Tea', 'Wellness', 'An uplifting blend of daisy and jasmine organic loose leaf tea. ( 4oz / 113g )', '10', '2.22', '27.99', null, '2'),
    ('8', 'Decorative Daisy Plush Pillow', 'Home', 'The perfect decorative pillow to brighten up any room', '10', '3.03', '11.99', null, '3'),
    ('9', 'Seize the Day Coffee Mug', 'Home', null, '10', '4.04', '12.99', null, '3'),
    ('10', 'Ease Your Travels Hydro Flask', 'Home', null, '10', '6.06', '24.99', null, '4'),
    ('11', 'Ceremonial Glass Tea Urn', 'Home', null, '10', '5.67', '17.99', null, '4'),
    ('12', 'Daisies for Days Bed Sheet Set', 'Home', null, '10', '21.21', '112.99', null, '4'),
    ('14', 'Soft Crossbody Briefcase', 'Travel', null, '10', '24.24', '89.99', null, '5'),
    ('15', 'Crossbody Messenger Bag', 'Travel', null, '10', '12.12', '39.99', null, '5'),
    ('16', 'Wanderlust Luggage Set', 'Travel', 'The perfect luggage set for your travel needs. Includes one carry-on sized luggage and one large luggage. Each piece is light and durable with a retractable handle and wheels.', '10', '53.53', '169.99', null, '5'),
    ('17', 'Trail Blazer Utility Backpack', 'Travel', null, '10', '8.08', '54.99', null, '5'),
    ('18', 'Perfect Fit Pullover Unisex Hoodie', 'Apparel', 'Our 100% cotton ultra soft unisex pullover hoodie feels like second skin of warmth and comfort. Neutral colors make it perfect for every day and all occasions. Available in colors Caramel, Coco, and Cream', '10', '11.11', '39.99', null, '6'),
    ('19', 'Cloud 9 Loungewear Set', 'Apparel', null, '10', '17.17', '59.99', null, '6'),
    ('20', 'Lazy Daisy Crew Socks', 'Apparel', '100% cotten, classic crew socks. Pack of 2 colors, Aloe and Azure.', '10', '4.04', '12.99', null, '6'),
    ('21', 'Outdoor Sports Cap', 'Apparel', '100% cotton, perfect fit outdoor sports cap. Available in colors Aloe and Mauve', '10', '6.06', '27.99', null, '7'),
    ('22', 'Sierra Skully Beanie', 'Apparel', '100% double layer cotton, thick and warm skull beanie. Perfect for the slopes, long treks, and winter wear. Available in colors Coffee and Vanilla.', '10', '10.1', '49.99', null, '7'),
    ('23', 'Pro Leather Iphone Case', 'Accessories', null, '10', '9.09', '39.99', null, '8'),
    ('24', 'Y2K Clear Iphone Case', 'Accessories', null, '10', '7.07', '19.99', null, '8'),
    ('25', 'Brains & Bloom Laptop Case', 'Accessories', null, '10', '11.12', '29.99', null, '8'),
    ('26', 'Go With The Flow ThermoFlask', 'Home, Travel', null, '10', '10.01', '35.99', null, '5'),
    ('27', 'Zen Daisy Glow Gummies', 'Wellness', null, '10', '13.13', '39.99', null, '2'),
    ('28', 'Stay Dry Daisy Umbrella', 'Accessories, Home', null, '10', '10.01', '39.99', null, '4');
